
// ********RoostGPT********
/*
Test generated by RoostGPT for test Nov-3-Gemini-Java-Maven using AI Type Gemini AI and AI Model gemini-2.5-pro

ROOST_METHOD_HASH=getAverage_cd4fabe1ad
ROOST_METHOD_SIG_HASH=getAverage_5d8b4919d3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/Nov-3-Gemini-Java-Maven/f8624cb1-a382-4f8a-a519-1bb96ce6e8df/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1005/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"

File Path: /var/tmp/Roost/RoostGPT/Nov-3-Gemini-Java-Maven/f8624cb1-a382-4f8a-a519-1bb96ce6e8df/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1006/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"Scenario 1: Calculate Average with Positive Integer Inputs

Details:
  TestName: getAverageWithPositiveIntegers
  Description: This test verifies that the getAverage method correctly calculates the weighted average when both 'a' and 'b' are set to positive integer values.
Execution:
  Arrange: Create an instance of the StudentGrade class. Set the value of 'a' to 10.0 and 'b' to 10.0 using the setA and setB methods.
  Act: Invoke the getAverage() method.
  Assert: Assert that the returned double value is equal to 10.0.
Validation:
  The test validates the basic functionality of the weighted average calculation with straightforward positive numbers. The expected result is (10.0 * 3.5 + 10.0 * 7.5) / 11.0, which simplifies to (35.0 + 75.0) / 11.0 = 110.0 / 11.0 = 10.0.


*/

// ********RoostGPT********

package br.masmangan.beecrowd.bee1005;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class StudentGradeGetAverageTest {

	@Test
	@Tag("valid")
	public void getAverageWithPositiveIntegers() {
		// Arrange
		StudentGrade studentGrade = new StudentGrade();
		studentGrade.setA(10.0);
		studentGrade.setB(10.0);
		// Act
		double result = studentGrade.getAverage();
		// Assert
		assertEquals(10.0, result, 0.00001);
	}

}