
// ********RoostGPT********
/*
Test generated by RoostGPT for test Nov-3-Gemini-Java-Maven using AI Type Gemini AI and AI Model gemini-2.5-pro

ROOST_METHOD_HASH=getAverage_3b87df4523
ROOST_METHOD_SIG_HASH=getAverage_5d8b4919d3

Here are your existing test cases which we found out and are not considered for test generation:

File Path: /var/tmp/Roost/RoostGPT/Nov-3-Gemini-Java-Maven/f8624cb1-a382-4f8a-a519-1bb96ce6e8df/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1005/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"

File Path: /var/tmp/Roost/RoostGPT/Nov-3-Gemini-Java-Maven/f8624cb1-a382-4f8a-a519-1bb96ce6e8df/source/java-cucumber/src/test/java/br/masmangan/beecrowd/bee1006/StudentGradeSteps.java
Tests:
    "@Test
public void average_is_calculated() {
    actual = equation.getAverage();
}
"Scenario 1: Calculate average with positive integer values

Details:
  TestName: getAverageWithPositiveIntegers
  Description: This test verifies that the getAverage method correctly calculates the weighted average when all three grades (a, b, c) are positive integers.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to 80.0, grade 'b' to 90.0, and grade 'c' to 100.0.
  Act: Invoke the getAverage() method on the StudentGrade instance.
  Assert: Assert that the returned average is equal to the expected value of 95.0.
Validation:
  Clarify: The assertion checks if the weighted average formula (a*2 + b*3 + c*5) / 10 is computed correctly. The expected result is (80*2 + 90*3 + 100*5) / 10 = (160 + 270 + 500) / 10 = 930 / 10 = 93.0.
  Elaborate: This is a fundamental success-path scenario, ensuring the core logic of the weighted average calculation works as intended with typical, whole-number grade inputs.

---
Scenario 2: Calculate average with positive decimal values

Details:
  TestName: getAverageWithPositiveDecimalValues
  Description: This test ensures the getAverage method accurately handles floating-point arithmetic when the input grades are decimal values.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to 75.5, grade 'b' to 85.5, and grade 'c' to 95.5.
  Act: Invoke the getAverage() method.
  Assert: Assert that the calculated average is equal to the expected value of 88.0, allowing for a small tolerance for floating-point inaccuracies.
Validation:
  Clarify: The assertion validates the calculation: (75.5*2.0 + 85.5*3.0 + 95.5*5.0) / 10.0 = (151.0 + 256.5 + 477.5) / 10.0 = 885.0 / 10.0 = 88.5.
  Elaborate: This test is important for verifying that the use of `double` for calculations maintains precision and produces the correct result with non-integer inputs, which are common in grading systems.

---
Scenario 3: Calculate average when all input values are zero

Details:
  TestName: getAverageWhenAllInputsAreZero
  Description: This test case checks the behavior of the getAverage method when all grades are zero. The expected outcome is an average of zero.
Execution:
  Arrange: Create an instance of StudentGrade. Set grades 'a', 'b', and 'c' to 0.0.
  Act: Call the getAverage() method.
  Assert: Assert that the result is exactly 0.0.
Validation:
  Clarify: The assertion confirms that (0*2.0 + 0*3.0 + 0*5.0) / 10.0 correctly evaluates to 0.0.
  Elaborate: This is a boundary condition test that ensures the calculation doesn't produce an unexpected result (like NaN or an error) when inputs are at their lower bound of zero, representing a student who scored nothing.

---
Scenario 4: Calculate average with a mix of positive and zero values

Details:
  TestName: getAverageWithMixedPositiveAndZeroValues
  Description: This test verifies the calculation when some, but not all, of the grades are zero.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to 90.0, grade 'b' to 0.0, and grade 'c' to 80.0.
  Act: Invoke the getAverage() method.
  Assert: Assert that the returned average is equal to the expected value of 58.0.
Validation:
  Clarify: The assertion checks the calculation: (90.0*2.0 + 0.0*3.0 + 80.0*5.0) / 10.0 = (180.0 + 0.0 + 400.0) / 10.0 = 580.0 / 10.0 = 58.0.
  Elaborate: This scenario ensures that zero-value grades are correctly factored into the weighted average without skewing the result improperly, accurately reflecting a situation where a student may have missed an assignment or failed a test.

---
Scenario 5: Calculate average with all negative values

Details:
  TestName: getAverageWithAllNegativeValues
  Description: This test case validates that the method correctly performs the calculation even when input values are negative, although negative grades are not typical.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to -10.0, grade 'b' to -20.0, and grade 'c' to -30.0.
  Act: Call the getAverage() method.
  Assert: Assert that the result is the expected negative average of -23.0.
Validation:
  Clarify: The assertion verifies the formula with negative numbers: (-10.0*2.0 + -20.0*3.0 + -30.0*5.0) / 10.0 = (-20.0 - 60.0 - 150.0) / 10.0 = -230.0 / 10.0 = -23.0.
  Elaborate: This edge case test confirms the mathematical robustness of the method. It ensures that the calculation logic is not limited to positive numbers and can handle any valid `double` value.

---
Scenario 6: Calculate average with a mix of positive and negative values

Details:
  TestName: getAverageWithMixedPositiveAndNegativeValues
  Description: This test checks the calculation's correctness when the grades include both positive and negative values.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to 100.0, grade 'b' to -50.0, and grade 'c' to 50.0.
  Act: Invoke the getAverage() method.
  Assert: Assert that the returned average is equal to the expected value of 30.0.
Validation:
  Clarify: The assertion validates the sum of positive and negative weighted values: (100.0*2.0 + -50.0*3.0 + 50.0*5.0) / 10.0 = (200.0 - 150.0 + 250.0) / 10.0 = 300.0 / 10.0 = 30.0.
  Elaborate: This scenario further tests the mathematical integrity of the method, ensuring it can correctly aggregate positive and negative terms before the final division.

---
Scenario 7: Calculate average with large input values

Details:
  TestName: getAverageWithLargeInputValues
  Description: This test uses large numbers for grades to ensure the calculation remains accurate and does not suffer from overflow or precision loss with high-magnitude inputs.
Execution:
  Arrange: Create an instance of StudentGrade. Set grade 'a' to 500000.0, grade 'b' to 1000000.0, and grade 'c' to 2000000.0.
  Act: Call the getAverage() method.
  Assert: Assert that the result is equal to the expected value of 1400000.0.
Validation:
  Clarify: The assertion confirms the calculation with large numbers: (500000*2 + 1000000*3 + 2000000*5) / 10 = (1000000 + 3000000 + 10000000) / 10 = 14000000 / 10 = 1400000.0.
  Elaborate: This stress test helps confirm that the `double` data type is sufficient to handle large values without unexpected behavior, ensuring the method is reliable even with unconventional inputs.

*/

// ********RoostGPT********

package br.masmangan.beecrowd.bee1006;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class StudentGradeGetAverageTest {

	private StudentGrade studentGrade;

	private static final double DELTA = 0.001;

	@BeforeEach
	public void setUp() {
		studentGrade = new StudentGrade();
	}

	@Test
	@Tag("valid")
	public void getAverageWithPositiveIntegers() {
		// Arrange
		studentGrade.setA(80.0);
		studentGrade.setB(90.0);
		studentGrade.setC(100.0);
		double expectedAverage = 93.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("valid")
	public void getAverageWithPositiveDecimalValues() {
		// Arrange
		studentGrade.setA(75.5);
		studentGrade.setB(85.5);
		studentGrade.setC(95.5);
		double expectedAverage = 88.5;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("boundary")
	public void getAverageWhenAllInputsAreZero() {
		// Arrange
		studentGrade.setA(0.0);
		studentGrade.setB(0.0);
		studentGrade.setC(0.0);
		double expectedAverage = 0.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("valid")
	public void getAverageWithMixedPositiveAndZeroValues() {
		// Arrange
		studentGrade.setA(90.0);
		studentGrade.setB(0.0);
		studentGrade.setC(80.0);
		double expectedAverage = 58.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("boundary")
	public void getAverageWithAllNegativeValues() {
		// Arrange
		studentGrade.setA(-10.0);
		studentGrade.setB(-20.0);
		studentGrade.setC(-30.0);
		double expectedAverage = -23.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("boundary")
	public void getAverageWithMixedPositiveAndNegativeValues() {
		// Arrange
		studentGrade.setA(100.0);
		studentGrade.setB(-50.0);
		studentGrade.setC(50.0);
		double expectedAverage = 30.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

	@Test
	@Tag("boundary")
	public void getAverageWithLargeInputValues() {
		// Arrange
		studentGrade.setA(500000.0);
		studentGrade.setB(1000000.0);
		studentGrade.setC(2000000.0);
		double expectedAverage = 1400000.0;
		// Act
		double actualAverage = studentGrade.getAverage();
		// Assert
		assertEquals(expectedAverage, actualAverage, DELTA);
	}

}